
var res = {
  bg_png : "/cocos2dmygame/assets/basepack/bg.png",
  bg_castle_png : "/cocos2dmygame/assets/basepack/bg_castle.png",
  blockerBody_png : "/cocos2dmygame/assets/basepack/Enemies/blockerBody.png",
  blockerMad_png : "/cocos2dmygame/assets/basepack/Enemies/blockerMad.png",
  blockerSad_png : "/cocos2dmygame/assets/basepack/Enemies/blockerSad.png",
  enemies_spritesheet_png : "/cocos2dmygame/assets/basepack/Enemies/enemies_spritesheet.png",
  enemies_spritesheet_txt : "/cocos2dmygame/assets/basepack/Enemies/enemies_spritesheet.txt",
  fishDead_png : "/cocos2dmygame/assets/basepack/Enemies/fishDead.png",
  fishSwim1_png : "/cocos2dmygame/assets/basepack/Enemies/fishSwim1.png",
  fishSwim2_png : "/cocos2dmygame/assets/basepack/Enemies/fishSwim2.png",
  flyDead_png : "/cocos2dmygame/assets/basepack/Enemies/flyDead.png",
  flyFly1_png : "/cocos2dmygame/assets/basepack/Enemies/flyFly1.png",
  flyFly2_png : "/cocos2dmygame/assets/basepack/Enemies/flyFly2.png",
  pokerMad_png : "/cocos2dmygame/assets/basepack/Enemies/pokerMad.png",
  pokerSad_png : "/cocos2dmygame/assets/basepack/Enemies/pokerSad.png",
  slimeDead_png : "/cocos2dmygame/assets/basepack/Enemies/slimeDead.png",
  slimeWalk1_png : "/cocos2dmygame/assets/basepack/Enemies/slimeWalk1.png",
  slimeWalk2_png : "/cocos2dmygame/assets/basepack/Enemies/slimeWalk2.png",
  snailShell_png : "/cocos2dmygame/assets/basepack/Enemies/snailShell.png",
  snailShell_upsidedown_png : "/cocos2dmygame/assets/basepack/Enemies/snailShell_upsidedown.png",
  snailWalk1_png : "/cocos2dmygame/assets/basepack/Enemies/snailWalk1.png",
  snailWalk2_png : "/cocos2dmygame/assets/basepack/Enemies/snailWalk2.png",
  hud_0_png : "/cocos2dmygame/assets/basepack/HUD/hud_0.png",
  hud_1_png : "/cocos2dmygame/assets/basepack/HUD/hud_1.png",
  hud_2_png : "/cocos2dmygame/assets/basepack/HUD/hud_2.png",
  hud_3_png : "/cocos2dmygame/assets/basepack/HUD/hud_3.png",
  hud_4_png : "/cocos2dmygame/assets/basepack/HUD/hud_4.png",
  hud_5_png : "/cocos2dmygame/assets/basepack/HUD/hud_5.png",
  hud_6_png : "/cocos2dmygame/assets/basepack/HUD/hud_6.png",
  hud_7_png : "/cocos2dmygame/assets/basepack/HUD/hud_7.png",
  hud_8_png : "/cocos2dmygame/assets/basepack/HUD/hud_8.png",
  hud_9_png : "/cocos2dmygame/assets/basepack/HUD/hud_9.png",
  hud_coins_png : "/cocos2dmygame/assets/basepack/HUD/hud_coins.png",
  hud_gem_blue_png : "/cocos2dmygame/assets/basepack/HUD/hud_gem_blue.png",
  hud_gem_green_png : "/cocos2dmygame/assets/basepack/HUD/hud_gem_green.png",
  hud_gem_red_png : "/cocos2dmygame/assets/basepack/HUD/hud_gem_red.png",
  hud_gem_yellow_png : "/cocos2dmygame/assets/basepack/HUD/hud_gem_yellow.png",
  hud_heartEmpty_png : "/cocos2dmygame/assets/basepack/HUD/hud_heartEmpty.png",
  hud_heartFull_png : "/cocos2dmygame/assets/basepack/HUD/hud_heartFull.png",
  hud_heartHalf_png : "/cocos2dmygame/assets/basepack/HUD/hud_heartHalf.png",
  hud_keyBlue_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyBlue.png",
  hud_keyBlue_disabled_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyBlue_disabled.png",
  hud_keyGreem_disabled_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyGreem_disabled.png",
  hud_keyGreen_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyGreen.png",
  hud_keyRed_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyRed.png",
  hud_keyRed_disabled_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyRed_disabled.png",
  hud_keyYellow_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyYellow.png",
  hud_keyYellow_disabled_png : "/cocos2dmygame/assets/basepack/HUD/hud_keyYellow_disabled.png",
  hud_p1_png : "/cocos2dmygame/assets/basepack/HUD/hud_p1.png",
  hud_p1Alt_png : "/cocos2dmygame/assets/basepack/HUD/hud_p1Alt.png",
  hud_p2_png : "/cocos2dmygame/assets/basepack/HUD/hud_p2.png",
  hud_p2Alt_png : "/cocos2dmygame/assets/basepack/HUD/hud_p2Alt.png",
  hud_p3_png : "/cocos2dmygame/assets/basepack/HUD/hud_p3.png",
  hud_p3Alt_png : "/cocos2dmygame/assets/basepack/HUD/hud_p3Alt.png",
  hud_spritesheet_png : "/cocos2dmygame/assets/basepack/HUD/hud_spritesheet.png",
  hud_spritesheet_xml : "/cocos2dmygame/assets/basepack/HUD/hud_spritesheet.xml",
  hud_x_png : "/cocos2dmygame/assets/basepack/HUD/hud_x.png",
  bomb_png : "/cocos2dmygame/assets/basepack/Items/bomb.png",
  bombFlash_png : "/cocos2dmygame/assets/basepack/Items/bombFlash.png",
  bush_png : "/cocos2dmygame/assets/basepack/Items/bush.png",
  buttonBlue_png : "/cocos2dmygame/assets/basepack/Items/buttonBlue.png",
  buttonBlue_pressed_png : "/cocos2dmygame/assets/basepack/Items/buttonBlue_pressed.png",
  buttonGreen_png : "/cocos2dmygame/assets/basepack/Items/buttonGreen.png",
  buttonGreen_pressed_png : "/cocos2dmygame/assets/basepack/Items/buttonGreen_pressed.png",
  buttonRed_png : "/cocos2dmygame/assets/basepack/Items/buttonRed.png",
  buttonRed_pressed_png : "/cocos2dmygame/assets/basepack/Items/buttonRed_pressed.png",
  buttonYellow_png : "/cocos2dmygame/assets/basepack/Items/buttonYellow.png",
  buttonYellow_pressed_png : "/cocos2dmygame/assets/basepack/Items/buttonYellow_pressed.png",
  cactus_png : "/cocos2dmygame/assets/basepack/Items/cactus.png",
  chain_png : "/cocos2dmygame/assets/basepack/Items/chain.png",
  cloud1_png : "/cocos2dmygame/assets/basepack/Items/cloud1.png",
  cloud2_png : "/cocos2dmygame/assets/basepack/Items/cloud2.png",
  cloud3_png : "/cocos2dmygame/assets/basepack/Items/cloud3.png",
  coinBronze_png : "/cocos2dmygame/assets/basepack/Items/coinBronze.png",
  coinGold_png : "/cocos2dmygame/assets/basepack/Items/coinGold.png",
  coinSilver_png : "/cocos2dmygame/assets/basepack/Items/coinSilver.png",
  fireball_png : "/cocos2dmygame/assets/basepack/Items/fireball.png",
  flagBlue_png : "/cocos2dmygame/assets/basepack/Items/flagBlue.png",
  flagBlue2_png : "/cocos2dmygame/assets/basepack/Items/flagBlue2.png",
  flagBlueHanging_png : "/cocos2dmygame/assets/basepack/Items/flagBlueHanging.png",
  flagGreen_png : "/cocos2dmygame/assets/basepack/Items/flagGreen.png",
  flagGreen2_png : "/cocos2dmygame/assets/basepack/Items/flagGreen2.png",
  flagGreenHanging_png : "/cocos2dmygame/assets/basepack/Items/flagGreenHanging.png",
  flagRed_png : "/cocos2dmygame/assets/basepack/Items/flagRed.png",
  flagRed2_png : "/cocos2dmygame/assets/basepack/Items/flagRed2.png",
  flagRedHanging_png : "/cocos2dmygame/assets/basepack/Items/flagRedHanging.png",
  flagYellow_png : "/cocos2dmygame/assets/basepack/Items/flagYellow.png",
  flagYellow2_png : "/cocos2dmygame/assets/basepack/Items/flagYellow2.png",
  flagYellowHanging_png : "/cocos2dmygame/assets/basepack/Items/flagYellowHanging.png",
  gemBlue_png : "/cocos2dmygame/assets/basepack/Items/gemBlue.png",
  gemGreen_png : "/cocos2dmygame/assets/basepack/Items/gemGreen.png",
  gemRed_png : "/cocos2dmygame/assets/basepack/Items/gemRed.png",
  gemYellow_png : "/cocos2dmygame/assets/basepack/Items/gemYellow.png",
  items_spritesheet_png : "/cocos2dmygame/assets/basepack/Items/items_spritesheet.png",
  items_spritesheet_xml : "/cocos2dmygame/assets/basepack/Items/items_spritesheet.xml",
  keyBlue_png : "/cocos2dmygame/assets/basepack/Items/keyBlue.png",
  keyGreen_png : "/cocos2dmygame/assets/basepack/Items/keyGreen.png",
  keyRed_png : "/cocos2dmygame/assets/basepack/Items/keyRed.png",
  keyYellow_png : "/cocos2dmygame/assets/basepack/Items/keyYellow.png",
  mushroomBrown_png : "/cocos2dmygame/assets/basepack/Items/mushroomBrown.png",
  mushroomRed_png : "/cocos2dmygame/assets/basepack/Items/mushroomRed.png",
  particleBrick1a_png : "/cocos2dmygame/assets/basepack/Items/particleBrick1a.png",
  particleBrick1b_png : "/cocos2dmygame/assets/basepack/Items/particleBrick1b.png",
  particleBrick2a_png : "/cocos2dmygame/assets/basepack/Items/particleBrick2a.png",
  particleBrick2b_png : "/cocos2dmygame/assets/basepack/Items/particleBrick2b.png",
  plant_png : "/cocos2dmygame/assets/basepack/Items/plant.png",
  plantPurple_png : "/cocos2dmygame/assets/basepack/Items/plantPurple.png",
  rock_png : "/cocos2dmygame/assets/basepack/Items/rock.png",
  snowhill_png : "/cocos2dmygame/assets/basepack/Items/snowhill.png",
  spikes_png : "/cocos2dmygame/assets/basepack/Items/spikes.png",
  springboardDown_png : "/cocos2dmygame/assets/basepack/Items/springboardDown.png",
  springboardUp_png : "/cocos2dmygame/assets/basepack/Items/springboardUp.png",
  star_png : "/cocos2dmygame/assets/basepack/Items/star.png",
  switchLeft_png : "/cocos2dmygame/assets/basepack/Items/switchLeft.png",
  switchMid_png : "/cocos2dmygame/assets/basepack/Items/switchMid.png",
  switchRight_png : "/cocos2dmygame/assets/basepack/Items/switchRight.png",
  weight_png : "/cocos2dmygame/assets/basepack/Items/weight.png",
  weightChained_png : "/cocos2dmygame/assets/basepack/Items/weightChained.png",
  p1_duck_png : "/cocos2dmygame/assets/basepack/Player/p1_duck.png",
  p1_front_png : "/cocos2dmygame/assets/basepack/Player/p1_front.png",
  p1_hurt_png : "/cocos2dmygame/assets/basepack/Player/p1_hurt.png",
  p1_jump_png : "/cocos2dmygame/assets/basepack/Player/p1_jump.png",
  p1_spritesheet_png : "/cocos2dmygame/assets/basepack/Player/p1_spritesheet.png",
  p1_spritesheet_txt : "/cocos2dmygame/assets/basepack/Player/p1_spritesheet.txt",
  p1_stand_png : "/cocos2dmygame/assets/basepack/Player/p1_stand.png",
  p1_walk_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/p1_walk.png",
  p1_walk01_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk01.png",
  p1_walk02_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk02.png",
  p1_walk03_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk03.png",
  p1_walk04_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk04.png",
  p1_walk05_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk05.png",
  p1_walk06_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk06.png",
  p1_walk07_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk07.png",
  p1_walk08_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk08.png",
  p1_walk09_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk09.png",
  p1_walk10_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk10.png",
  p1_walk11_png : "/cocos2dmygame/assets/basepack/Player/p1_walk/PNG/p1_walk11.png",
  p2_duck_png : "/cocos2dmygame/assets/basepack/Player/p2_duck.png",
  p2_front_png : "/cocos2dmygame/assets/basepack/Player/p2_front.png",
  p2_hurt_png : "/cocos2dmygame/assets/basepack/Player/p2_hurt.png",
  p2_jump_png : "/cocos2dmygame/assets/basepack/Player/p2_jump.png",
  p2_spritesheet_png : "/cocos2dmygame/assets/basepack/Player/p2_spritesheet.png",
  p2_spritesheet_txt : "/cocos2dmygame/assets/basepack/Player/p2_spritesheet.txt",
  p2_stand_png : "/cocos2dmygame/assets/basepack/Player/p2_stand.png",
  p2_walk_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/p2_walk.png",
  p2_walk01_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk01.png",
  p2_walk02_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk02.png",
  p2_walk03_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk03.png",
  p2_walk04_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk04.png",
  p2_walk05_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk05.png",
  p2_walk06_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk06.png",
  p2_walk07_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk07.png",
  p2_walk08_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk08.png",
  p2_walk09_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk09.png",
  p2_walk10_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk10.png",
  p2_walk11_png : "/cocos2dmygame/assets/basepack/Player/p2_walk/PNG/p2_walk11.png",
  p3_duck_png : "/cocos2dmygame/assets/basepack/Player/p3_duck.png",
  p3_front_png : "/cocos2dmygame/assets/basepack/Player/p3_front.png",
  p3_hurt_png : "/cocos2dmygame/assets/basepack/Player/p3_hurt.png",
  p3_jump_png : "/cocos2dmygame/assets/basepack/Player/p3_jump.png",
  p3_spritesheet_png : "/cocos2dmygame/assets/basepack/Player/p3_spritesheet.png",
  p3_spritesheet_txt : "/cocos2dmygame/assets/basepack/Player/p3_spritesheet.txt",
  p3_stand_png : "/cocos2dmygame/assets/basepack/Player/p3_stand.png",
  p3_walk_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/p3_walk.png",
  p3_walk01_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk01.png",
  p3_walk02_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk02.png",
  p3_walk03_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk03.png",
  p3_walk04_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk04.png",
  p3_walk05_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk05.png",
  p3_walk06_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk06.png",
  p3_walk07_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk07.png",
  p3_walk08_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk08.png",
  p3_walk09_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk09.png",
  p3_walk10_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk10.png",
  p3_walk11_png : "/cocos2dmygame/assets/basepack/Player/p3_walk/PNG/p3_walk11.png",
  preview_png : "/cocos2dmygame/assets/basepack/preview.png",
  sample_png : "/cocos2dmygame/assets/basepack/sample.png",
  box_png : "/cocos2dmygame/assets/basepack/Tiles/box.png",
  boxAlt_png : "/cocos2dmygame/assets/basepack/Tiles/boxAlt.png",
  boxCoin_png : "/cocos2dmygame/assets/basepack/Tiles/boxCoin.png",
  boxCoinAlt_png : "/cocos2dmygame/assets/basepack/Tiles/boxCoinAlt.png",
  boxCoinAlt_disabled_png : "/cocos2dmygame/assets/basepack/Tiles/boxCoinAlt_disabled.png",
  boxCoin_disabled_png : "/cocos2dmygame/assets/basepack/Tiles/boxCoin_disabled.png",
  boxEmpty_png : "/cocos2dmygame/assets/basepack/Tiles/boxEmpty.png",
  boxExplosive_png : "/cocos2dmygame/assets/basepack/Tiles/boxExplosive.png",
  boxExplosiveAlt_png : "/cocos2dmygame/assets/basepack/Tiles/boxExplosiveAlt.png",
  boxExplosive_disabled_png : "/cocos2dmygame/assets/basepack/Tiles/boxExplosive_disabled.png",
  boxItem_png : "/cocos2dmygame/assets/basepack/Tiles/boxItem.png",
  boxItemAlt_png : "/cocos2dmygame/assets/basepack/Tiles/boxItemAlt.png",
  boxItemAlt_disabled_png : "/cocos2dmygame/assets/basepack/Tiles/boxItemAlt_disabled.png",
  boxItem_disabled_png : "/cocos2dmygame/assets/basepack/Tiles/boxItem_disabled.png",
  boxWarning_png : "/cocos2dmygame/assets/basepack/Tiles/boxWarning.png",
  brickWall_png : "/cocos2dmygame/assets/basepack/Tiles/brickWall.png",
  bridge_png : "/cocos2dmygame/assets/basepack/Tiles/bridge.png",
  bridgeLogs_png : "/cocos2dmygame/assets/basepack/Tiles/bridgeLogs.png",
  castle_png : "/cocos2dmygame/assets/basepack/Tiles/castle.png",
  castleCenter_png : "/cocos2dmygame/assets/basepack/Tiles/castleCenter.png",
  castleCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/castleCenter_rounded.png",
  castleCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/castleCliffLeft.png",
  castleCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/castleCliffLeftAlt.png",
  castleCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/castleCliffRight.png",
  castleCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/castleCliffRightAlt.png",
  castleHalf_png : "/cocos2dmygame/assets/basepack/Tiles/castleHalf.png",
  castleHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/castleHalfLeft.png",
  castleHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/castleHalfMid.png",
  castleHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/castleHalfRight.png",
  castleHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/castleHillLeft.png",
  castleHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/castleHillLeft2.png",
  castleHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/castleHillRight.png",
  castleHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/castleHillRight2.png",
  castleLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/castleLedgeLeft.png",
  castleLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/castleLedgeRight.png",
  castleLeft_png : "/cocos2dmygame/assets/basepack/Tiles/castleLeft.png",
  castleMid_png : "/cocos2dmygame/assets/basepack/Tiles/castleMid.png",
  castleRight_png : "/cocos2dmygame/assets/basepack/Tiles/castleRight.png",
  dirt_png : "/cocos2dmygame/assets/basepack/Tiles/dirt.png",
  dirtCenter_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCenter.png",
  dirtCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCenter_rounded.png",
  dirtCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCliffLeft.png",
  dirtCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCliffLeftAlt.png",
  dirtCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCliffRight.png",
  dirtCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/dirtCliffRightAlt.png",
  dirtHalf_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHalf.png",
  dirtHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHalfLeft.png",
  dirtHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHalfMid.png",
  dirtHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHalfRight.png",
  dirtHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHillLeft.png",
  dirtHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHillLeft2.png",
  dirtHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHillRight.png",
  dirtHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/dirtHillRight2.png",
  dirtLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/dirtLedgeLeft.png",
  dirtLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/dirtLedgeRight.png",
  dirtLeft_png : "/cocos2dmygame/assets/basepack/Tiles/dirtLeft.png",
  dirtMid_png : "/cocos2dmygame/assets/basepack/Tiles/dirtMid.png",
  dirtRight_png : "/cocos2dmygame/assets/basepack/Tiles/dirtRight.png",
  door_closedMid_png : "/cocos2dmygame/assets/basepack/Tiles/door_closedMid.png",
  door_closedTop_png : "/cocos2dmygame/assets/basepack/Tiles/door_closedTop.png",
  door_openMid_png : "/cocos2dmygame/assets/basepack/Tiles/door_openMid.png",
  door_openTop_png : "/cocos2dmygame/assets/basepack/Tiles/door_openTop.png",
  fence_png : "/cocos2dmygame/assets/basepack/Tiles/fence.png",
  fenceBroken_png : "/cocos2dmygame/assets/basepack/Tiles/fenceBroken.png",
  grass_png : "/cocos2dmygame/assets/basepack/Tiles/grass.png",
  grassCenter_png : "/cocos2dmygame/assets/basepack/Tiles/grassCenter.png",
  grassCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/grassCenter_rounded.png",
  grassCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/grassCliffLeft.png",
  grassCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/grassCliffLeftAlt.png",
  grassCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/grassCliffRight.png",
  grassCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/grassCliffRightAlt.png",
  grassHalf_png : "/cocos2dmygame/assets/basepack/Tiles/grassHalf.png",
  grassHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/grassHalfLeft.png",
  grassHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/grassHalfMid.png",
  grassHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/grassHalfRight.png",
  grassHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/grassHillLeft.png",
  grassHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/grassHillLeft2.png",
  grassHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/grassHillRight.png",
  grassHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/grassHillRight2.png",
  grassLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/grassLedgeLeft.png",
  grassLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/grassLedgeRight.png",
  grassLeft_png : "/cocos2dmygame/assets/basepack/Tiles/grassLeft.png",
  grassMid_png : "/cocos2dmygame/assets/basepack/Tiles/grassMid.png",
  grassRight_png : "/cocos2dmygame/assets/basepack/Tiles/grassRight.png",
  hill_large_png : "/cocos2dmygame/assets/basepack/Tiles/hill_large.png",
  hill_largeAlt_png : "/cocos2dmygame/assets/basepack/Tiles/hill_largeAlt.png",
  hill_small_png : "/cocos2dmygame/assets/basepack/Tiles/hill_small.png",
  hill_smallAlt_png : "/cocos2dmygame/assets/basepack/Tiles/hill_smallAlt.png",
  ladder_mid_png : "/cocos2dmygame/assets/basepack/Tiles/ladder_mid.png",
  ladder_top_png : "/cocos2dmygame/assets/basepack/Tiles/ladder_top.png",
  liquidLava_png : "/cocos2dmygame/assets/basepack/Tiles/liquidLava.png",
  liquidLavaTop_png : "/cocos2dmygame/assets/basepack/Tiles/liquidLavaTop.png",
  liquidLavaTop_mid_png : "/cocos2dmygame/assets/basepack/Tiles/liquidLavaTop_mid.png",
  liquidWater_png : "/cocos2dmygame/assets/basepack/Tiles/liquidWater.png",
  liquidWaterTop_png : "/cocos2dmygame/assets/basepack/Tiles/liquidWaterTop.png",
  liquidWaterTop_mid_png : "/cocos2dmygame/assets/basepack/Tiles/liquidWaterTop_mid.png",
  lock_blue_png : "/cocos2dmygame/assets/basepack/Tiles/lock_blue.png",
  lock_green_png : "/cocos2dmygame/assets/basepack/Tiles/lock_green.png",
  lock_red_png : "/cocos2dmygame/assets/basepack/Tiles/lock_red.png",
  lock_yellow_png : "/cocos2dmygame/assets/basepack/Tiles/lock_yellow.png",
  rockHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/rockHillLeft.png",
  rockHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/rockHillRight.png",
  ropeAttached_png : "/cocos2dmygame/assets/basepack/Tiles/ropeAttached.png",
  ropeHorizontal_png : "/cocos2dmygame/assets/basepack/Tiles/ropeHorizontal.png",
  ropeVertical_png : "/cocos2dmygame/assets/basepack/Tiles/ropeVertical.png",
  sand_png : "/cocos2dmygame/assets/basepack/Tiles/sand.png",
  sandCenter_png : "/cocos2dmygame/assets/basepack/Tiles/sandCenter.png",
  sandCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/sandCenter_rounded.png",
  sandCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/sandCliffLeft.png",
  sandCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/sandCliffLeftAlt.png",
  sandCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/sandCliffRight.png",
  sandCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/sandCliffRightAlt.png",
  sandHalf_png : "/cocos2dmygame/assets/basepack/Tiles/sandHalf.png",
  sandHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/sandHalfLeft.png",
  sandHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/sandHalfMid.png",
  sandHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/sandHalfRight.png",
  sandHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/sandHillLeft.png",
  sandHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/sandHillLeft2.png",
  sandHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/sandHillRight.png",
  sandHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/sandHillRight2.png",
  sandLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/sandLedgeLeft.png",
  sandLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/sandLedgeRight.png",
  sandLeft_png : "/cocos2dmygame/assets/basepack/Tiles/sandLeft.png",
  sandMid_png : "/cocos2dmygame/assets/basepack/Tiles/sandMid.png",
  sandRight_png : "/cocos2dmygame/assets/basepack/Tiles/sandRight.png",
  sign_png : "/cocos2dmygame/assets/basepack/Tiles/sign.png",
  signExit_png : "/cocos2dmygame/assets/basepack/Tiles/signExit.png",
  signLeft_png : "/cocos2dmygame/assets/basepack/Tiles/signLeft.png",
  signRight_png : "/cocos2dmygame/assets/basepack/Tiles/signRight.png",
  snow_png : "/cocos2dmygame/assets/basepack/Tiles/snow.png",
  snowCenter_png : "/cocos2dmygame/assets/basepack/Tiles/snowCenter.png",
  snowCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/snowCenter_rounded.png",
  snowCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/snowCliffLeft.png",
  snowCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/snowCliffLeftAlt.png",
  snowCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/snowCliffRight.png",
  snowCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/snowCliffRightAlt.png",
  snowHalf_png : "/cocos2dmygame/assets/basepack/Tiles/snowHalf.png",
  snowHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/snowHalfLeft.png",
  snowHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/snowHalfMid.png",
  snowHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/snowHalfRight.png",
  snowHillLeft_png : "/cocos2dmygame/assets/basepack/Tiles/snowHillLeft.png",
  snowHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/snowHillLeft2.png",
  snowHillRight_png : "/cocos2dmygame/assets/basepack/Tiles/snowHillRight.png",
  snowHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/snowHillRight2.png",
  snowLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/snowLedgeLeft.png",
  snowLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/snowLedgeRight.png",
  snowLeft_png : "/cocos2dmygame/assets/basepack/Tiles/snowLeft.png",
  snowMid_png : "/cocos2dmygame/assets/basepack/Tiles/snowMid.png",
  snowRight_png : "/cocos2dmygame/assets/basepack/Tiles/snowRight.png",
  stone_png : "/cocos2dmygame/assets/basepack/Tiles/stone.png",
  stoneCenter_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCenter.png",
  stoneCenter_rounded_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCenter_rounded.png",
  stoneCliffLeft_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCliffLeft.png",
  stoneCliffLeftAlt_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCliffLeftAlt.png",
  stoneCliffRight_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCliffRight.png",
  stoneCliffRightAlt_png : "/cocos2dmygame/assets/basepack/Tiles/stoneCliffRightAlt.png",
  stoneHalf_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHalf.png",
  stoneHalfLeft_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHalfLeft.png",
  stoneHalfMid_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHalfMid.png",
  stoneHalfRight_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHalfRight.png",
  stoneHillLeft2_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHillLeft2.png",
  stoneHillRight2_png : "/cocos2dmygame/assets/basepack/Tiles/stoneHillRight2.png",
  stoneLedgeLeft_png : "/cocos2dmygame/assets/basepack/Tiles/stoneLedgeLeft.png",
  stoneLedgeRight_png : "/cocos2dmygame/assets/basepack/Tiles/stoneLedgeRight.png",
  stoneLeft_png : "/cocos2dmygame/assets/basepack/Tiles/stoneLeft.png",
  stoneMid_png : "/cocos2dmygame/assets/basepack/Tiles/stoneMid.png",
  stoneRight_png : "/cocos2dmygame/assets/basepack/Tiles/stoneRight.png",
  stoneWall_png : "/cocos2dmygame/assets/basepack/Tiles/stoneWall.png",
  tiles_spritesheet_png : "/cocos2dmygame/assets/basepack/Tiles/tiles_spritesheet.png",
  tiles_spritesheet_xml : "/cocos2dmygame/assets/basepack/Tiles/tiles_spritesheet.xml",
  tochLit_png : "/cocos2dmygame/assets/basepack/Tiles/tochLit.png",
  tochLit2_png : "/cocos2dmygame/assets/basepack/Tiles/tochLit2.png",
  torch_png : "/cocos2dmygame/assets/basepack/Tiles/torch.png",
  window_png : "/cocos2dmygame/assets/basepack/Tiles/window.png",
  characters_svg : "/cocos2dmygame/assets/basepack/Vector/characters.svg",
  enemies_svg : "/cocos2dmygame/assets/basepack/Vector/enemies.svg",
  tiles_svg : "/cocos2dmygame/assets/basepack/Vector/tiles.svg",
  cover_png : "/cocos2dmygame/assets/book/cover.png",
  tile_0_png : "/cocos2dmygame/assets/book/tile_0.png",
  tile_1_png : "/cocos2dmygame/assets/book/tile_1.png",
  tile_2_png : "/cocos2dmygame/assets/book/tile_2.png",
  tile_3_png : "/cocos2dmygame/assets/book/tile_3.png",
  tile_4_png : "/cocos2dmygame/assets/book/tile_4.png",
  tile_5_png : "/cocos2dmygame/assets/book/tile_5.png",
  tile_6_png : "/cocos2dmygame/assets/book/tile_6.png",
  tile_7_png : "/cocos2dmygame/assets/book/tile_7.png",
  group_png : "/cocos2dmygame/assets/group.png",
  HelloWorld_png : "/cocos2dmygame/assets/HelloWorld.png",

};    
        
var gameResources = [
  res.bg_png,
  res.bg_castle_png,
  res.blockerBody_png,
  res.blockerMad_png,
  res.blockerSad_png,
  res.enemies_spritesheet_png,
  res.enemies_spritesheet_txt,
  res.fishDead_png,
  res.fishSwim1_png,
  res.fishSwim2_png,
  res.flyDead_png,
  res.flyFly1_png,
  res.flyFly2_png,
  res.pokerMad_png,
  res.pokerSad_png,
  res.slimeDead_png,
  res.slimeWalk1_png,
  res.slimeWalk2_png,
  res.snailShell_png,
  res.snailShell_upsidedown_png,
  res.snailWalk1_png,
  res.snailWalk2_png,
  res.hud_0_png,
  res.hud_1_png,
  res.hud_2_png,
  res.hud_3_png,
  res.hud_4_png,
  res.hud_5_png,
  res.hud_6_png,
  res.hud_7_png,
  res.hud_8_png,
  res.hud_9_png,
  res.hud_coins_png,
  res.hud_gem_blue_png,
  res.hud_gem_green_png,
  res.hud_gem_red_png,
  res.hud_gem_yellow_png,
  res.hud_heartEmpty_png,
  res.hud_heartFull_png,
  res.hud_heartHalf_png,
  res.hud_keyBlue_png,
  res.hud_keyBlue_disabled_png,
  res.hud_keyGreem_disabled_png,
  res.hud_keyGreen_png,
  res.hud_keyRed_png,
  res.hud_keyRed_disabled_png,
  res.hud_keyYellow_png,
  res.hud_keyYellow_disabled_png,
  res.hud_p1_png,
  res.hud_p1Alt_png,
  res.hud_p2_png,
  res.hud_p2Alt_png,
  res.hud_p3_png,
  res.hud_p3Alt_png,
  res.hud_spritesheet_png,
  res.hud_spritesheet_xml,
  res.hud_x_png,
  res.bomb_png,
  res.bombFlash_png,
  res.bush_png,
  res.buttonBlue_png,
  res.buttonBlue_pressed_png,
  res.buttonGreen_png,
  res.buttonGreen_pressed_png,
  res.buttonRed_png,
  res.buttonRed_pressed_png,
  res.buttonYellow_png,
  res.buttonYellow_pressed_png,
  res.cactus_png,
  res.chain_png,
  res.cloud1_png,
  res.cloud2_png,
  res.cloud3_png,
  res.coinBronze_png,
  res.coinGold_png,
  res.coinSilver_png,
  res.fireball_png,
  res.flagBlue_png,
  res.flagBlue2_png,
  res.flagBlueHanging_png,
  res.flagGreen_png,
  res.flagGreen2_png,
  res.flagGreenHanging_png,
  res.flagRed_png,
  res.flagRed2_png,
  res.flagRedHanging_png,
  res.flagYellow_png,
  res.flagYellow2_png,
  res.flagYellowHanging_png,
  res.gemBlue_png,
  res.gemGreen_png,
  res.gemRed_png,
  res.gemYellow_png,
  res.items_spritesheet_png,
  res.items_spritesheet_xml,
  res.keyBlue_png,
  res.keyGreen_png,
  res.keyRed_png,
  res.keyYellow_png,
  res.mushroomBrown_png,
  res.mushroomRed_png,
  res.particleBrick1a_png,
  res.particleBrick1b_png,
  res.particleBrick2a_png,
  res.particleBrick2b_png,
  res.plant_png,
  res.plantPurple_png,
  res.rock_png,
  res.snowhill_png,
  res.spikes_png,
  res.springboardDown_png,
  res.springboardUp_png,
  res.star_png,
  res.switchLeft_png,
  res.switchMid_png,
  res.switchRight_png,
  res.weight_png,
  res.weightChained_png,
  res.p1_duck_png,
  res.p1_front_png,
  res.p1_hurt_png,
  res.p1_jump_png,
  res.p1_spritesheet_png,
  res.p1_spritesheet_txt,
  res.p1_stand_png,
  res.p1_walk_png,
  res.p1_walk01_png,
  res.p1_walk02_png,
  res.p1_walk03_png,
  res.p1_walk04_png,
  res.p1_walk05_png,
  res.p1_walk06_png,
  res.p1_walk07_png,
  res.p1_walk08_png,
  res.p1_walk09_png,
  res.p1_walk10_png,
  res.p1_walk11_png,
  res.p2_duck_png,
  res.p2_front_png,
  res.p2_hurt_png,
  res.p2_jump_png,
  res.p2_spritesheet_png,
  res.p2_spritesheet_txt,
  res.p2_stand_png,
  res.p2_walk_png,
  res.p2_walk01_png,
  res.p2_walk02_png,
  res.p2_walk03_png,
  res.p2_walk04_png,
  res.p2_walk05_png,
  res.p2_walk06_png,
  res.p2_walk07_png,
  res.p2_walk08_png,
  res.p2_walk09_png,
  res.p2_walk10_png,
  res.p2_walk11_png,
  res.p3_duck_png,
  res.p3_front_png,
  res.p3_hurt_png,
  res.p3_jump_png,
  res.p3_spritesheet_png,
  res.p3_spritesheet_txt,
  res.p3_stand_png,
  res.p3_walk_png,
  res.p3_walk01_png,
  res.p3_walk02_png,
  res.p3_walk03_png,
  res.p3_walk04_png,
  res.p3_walk05_png,
  res.p3_walk06_png,
  res.p3_walk07_png,
  res.p3_walk08_png,
  res.p3_walk09_png,
  res.p3_walk10_png,
  res.p3_walk11_png,
  res.preview_png,
  res.sample_png,
  res.box_png,
  res.boxAlt_png,
  res.boxCoin_png,
  res.boxCoinAlt_png,
  res.boxCoinAlt_disabled_png,
  res.boxCoin_disabled_png,
  res.boxEmpty_png,
  res.boxExplosive_png,
  res.boxExplosiveAlt_png,
  res.boxExplosive_disabled_png,
  res.boxItem_png,
  res.boxItemAlt_png,
  res.boxItemAlt_disabled_png,
  res.boxItem_disabled_png,
  res.boxWarning_png,
  res.brickWall_png,
  res.bridge_png,
  res.bridgeLogs_png,
  res.castle_png,
  res.castleCenter_png,
  res.castleCenter_rounded_png,
  res.castleCliffLeft_png,
  res.castleCliffLeftAlt_png,
  res.castleCliffRight_png,
  res.castleCliffRightAlt_png,
  res.castleHalf_png,
  res.castleHalfLeft_png,
  res.castleHalfMid_png,
  res.castleHalfRight_png,
  res.castleHillLeft_png,
  res.castleHillLeft2_png,
  res.castleHillRight_png,
  res.castleHillRight2_png,
  res.castleLedgeLeft_png,
  res.castleLedgeRight_png,
  res.castleLeft_png,
  res.castleMid_png,
  res.castleRight_png,
  res.dirt_png,
  res.dirtCenter_png,
  res.dirtCenter_rounded_png,
  res.dirtCliffLeft_png,
  res.dirtCliffLeftAlt_png,
  res.dirtCliffRight_png,
  res.dirtCliffRightAlt_png,
  res.dirtHalf_png,
  res.dirtHalfLeft_png,
  res.dirtHalfMid_png,
  res.dirtHalfRight_png,
  res.dirtHillLeft_png,
  res.dirtHillLeft2_png,
  res.dirtHillRight_png,
  res.dirtHillRight2_png,
  res.dirtLedgeLeft_png,
  res.dirtLedgeRight_png,
  res.dirtLeft_png,
  res.dirtMid_png,
  res.dirtRight_png,
  res.door_closedMid_png,
  res.door_closedTop_png,
  res.door_openMid_png,
  res.door_openTop_png,
  res.fence_png,
  res.fenceBroken_png,
  res.grass_png,
  res.grassCenter_png,
  res.grassCenter_rounded_png,
  res.grassCliffLeft_png,
  res.grassCliffLeftAlt_png,
  res.grassCliffRight_png,
  res.grassCliffRightAlt_png,
  res.grassHalf_png,
  res.grassHalfLeft_png,
  res.grassHalfMid_png,
  res.grassHalfRight_png,
  res.grassHillLeft_png,
  res.grassHillLeft2_png,
  res.grassHillRight_png,
  res.grassHillRight2_png,
  res.grassLedgeLeft_png,
  res.grassLedgeRight_png,
  res.grassLeft_png,
  res.grassMid_png,
  res.grassRight_png,
  res.hill_large_png,
  res.hill_largeAlt_png,
  res.hill_small_png,
  res.hill_smallAlt_png,
  res.ladder_mid_png,
  res.ladder_top_png,
  res.liquidLava_png,
  res.liquidLavaTop_png,
  res.liquidLavaTop_mid_png,
  res.liquidWater_png,
  res.liquidWaterTop_png,
  res.liquidWaterTop_mid_png,
  res.lock_blue_png,
  res.lock_green_png,
  res.lock_red_png,
  res.lock_yellow_png,
  res.rockHillLeft_png,
  res.rockHillRight_png,
  res.ropeAttached_png,
  res.ropeHorizontal_png,
  res.ropeVertical_png,
  res.sand_png,
  res.sandCenter_png,
  res.sandCenter_rounded_png,
  res.sandCliffLeft_png,
  res.sandCliffLeftAlt_png,
  res.sandCliffRight_png,
  res.sandCliffRightAlt_png,
  res.sandHalf_png,
  res.sandHalfLeft_png,
  res.sandHalfMid_png,
  res.sandHalfRight_png,
  res.sandHillLeft_png,
  res.sandHillLeft2_png,
  res.sandHillRight_png,
  res.sandHillRight2_png,
  res.sandLedgeLeft_png,
  res.sandLedgeRight_png,
  res.sandLeft_png,
  res.sandMid_png,
  res.sandRight_png,
  res.sign_png,
  res.signExit_png,
  res.signLeft_png,
  res.signRight_png,
  res.snow_png,
  res.snowCenter_png,
  res.snowCenter_rounded_png,
  res.snowCliffLeft_png,
  res.snowCliffLeftAlt_png,
  res.snowCliffRight_png,
  res.snowCliffRightAlt_png,
  res.snowHalf_png,
  res.snowHalfLeft_png,
  res.snowHalfMid_png,
  res.snowHalfRight_png,
  res.snowHillLeft_png,
  res.snowHillLeft2_png,
  res.snowHillRight_png,
  res.snowHillRight2_png,
  res.snowLedgeLeft_png,
  res.snowLedgeRight_png,
  res.snowLeft_png,
  res.snowMid_png,
  res.snowRight_png,
  res.stone_png,
  res.stoneCenter_png,
  res.stoneCenter_rounded_png,
  res.stoneCliffLeft_png,
  res.stoneCliffLeftAlt_png,
  res.stoneCliffRight_png,
  res.stoneCliffRightAlt_png,
  res.stoneHalf_png,
  res.stoneHalfLeft_png,
  res.stoneHalfMid_png,
  res.stoneHalfRight_png,
  res.stoneHillLeft2_png,
  res.stoneHillRight2_png,
  res.stoneLedgeLeft_png,
  res.stoneLedgeRight_png,
  res.stoneLeft_png,
  res.stoneMid_png,
  res.stoneRight_png,
  res.stoneWall_png,
  res.tiles_spritesheet_png,
  res.tiles_spritesheet_xml,
  res.tochLit_png,
  res.tochLit2_png,
  res.torch_png,
  res.window_png,
  res.characters_svg,
  res.enemies_svg,
  res.tiles_svg,
  res.cover_png,
  res.tile_0_png,
  res.tile_1_png,
  res.tile_2_png,
  res.tile_3_png,
  res.tile_4_png,
  res.tile_5_png,
  res.tile_6_png,
  res.tile_7_png,
  res.group_png,
  res.HelloWorld_png,

];